services:
  nginx:
    build:
      context: ./requirements/
      dockerfile: nginx/Dockerfile
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - wp-data:/var/www/html:ro
    networks:
      - incep
    depends_on:
      - wordpress
    restart: always
  mariadb:
    build: ./requirements/mariadb/.
    container_name: mariadb
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - incep
    env_file:
      - .env
    restart: on-failure
  wordpress:
    build: ./requirements/wordpress/.
    container_name: wordpress
    volumes:
      - wp-data:/var/www/html
    networks:
      - incep
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    ports:
      - "127.0.0.1:9000:443"

volumes:
  wp-data:
    name: "wp-vol"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mlouis/data/wordpress
      # device: /Users/louism/prog/inception/data/wordpress
  db-data:
    name: "db-vol"
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mlouis/data/mariadb
      # device: /Users/louism/prog/inception/data/mariadb

networks:
  incep:
    name: inc-network
